In [2]:
import numpy as np
from collections import deque, namedtuple
import time
import random

In [3]:
memory = deque(maxlen=3)

In [4]:
experience = namedtuple("Experience", field_names=[ "action"])

In [5]:
e = experience(np.random.choice([1, 2, 3 ,4, 5 ,6 ,7 ,8 ]))
print(e)

Experience(action=7)


In [6]:
memory.append(e)

In [7]:
print(memory)

deque([Experience(action=7)], maxlen=3)


In [8]:
class Testing():
    def __init__(self):
        self.t_step=1
        self.UPD=2
        self.TAR=8
        
    def step(self):
        if(self.t_step%self.UPD)==0:
            self.update1()
        print(self.t_step)
        self.t_step+=1
        
    def update1(self):
        print("Policy Updated")
        if(self.t_step%self.TAR)==0:
            self.update2()
            
    def update2(self):
        print("Target Updated")
    

In [9]:
tes=Testing()

In [10]:
tes.step()

1


In [11]:
action_values=np.array([52, 53, 53, 49])
print(np.argmax(action_values))
max_acts=np.argwhere(action_values==np.amax(action_values))
print(max_acts)
print(random.choice(max_acts.reshape(-1)))

1
[[1]
 [2]]
1


In [12]:
print(np.arange(4))

[0 1 2 3]


In [31]:
action_values=np.array([123, 52 ,123 ,99])

In [32]:
acts = [0,2,3]

In [33]:
action_values = [action_values[i] for i in acts]
print(action_values)

[123, 123, 99]


In [34]:
max_acts = np.argwhere(action_values==np.amax(action_values))
print(max_acts)

[[0]
 [1]]


In [45]:
action = np.random.choice([acts[i] for i in max_acts.reshape(-1)])
print(action)

0


In [1]:
ga=[ 10, 9, 8, 7, 6, 5, 4, 3,2,1, 0]

In [3]:
ga[-6:-1]

[5, 4, 3, 2, 1]